build-job:
  stage: build
  script:
    - echo "Checking environment files"
    - ls -la
    - echo "Installing dependencies for GUI component"
    - apt-get update && apt-get install -y libsfml-dev g++
    - echo "Starting build process"
    - make re
  artifacts:
    paths:
      - zappy_server
      - zappy_gui
      - zappy_ai
    expire_in: 1 day

verify-executables:
  stage: test
  needs:
    - job: build-job
      artifacts: true
  script:
    - echo "Checking files in test environment"
    - ls -la
    - echo "Verifying server executable"
    - |
      if [ -f "zappy_server" ] && [ -x "zappy_server" ]; then
        echo "✅ zappy_server exists and is executable";
      else
        echo "❌ ERROR: zappy_server doesn't exist or isn't executable";
        exit 1;
      fi
    - echo "Verifying GUI executable"
    - |
      if [ -f "zappy_gui" ] && [ -x "zappy_gui" ]; then
        echo "✅ zappy_gui exists and is executable";
      else
        echo "❌ ERROR: zappy_gui doesn't exist or isn't executable";
        exit 1;
      fi
    - echo "Verifying AI executable"
    - |
      if [ -f "zappy_ai" ] && [ -x "zappy_ai" ]; then
        echo "✅ zappy_ai exists and is executable";
      else
        echo "❌ ERROR: zappy_ai doesn't exist or isn't executable";
        exit 1;
      fi