#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Zappy AI Client executable
"""

import os
import sys

# Add the parent directory to the path so we can import modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import the main function from the main module
from zappy_ai.main import main

if __name__ == "__main__":
    # Execute the main function
    main()
